### ISSUE TITLE
CustomEnderchest compatibility

### ISSUE THREAD

**Issue by Twonox** [lishid/OpenInv#48]
Could you make a compatible /openender command with the plugins `CustomEnderchest` please?

> http://dev.bukkit.org/bukkit-plugins/custom-enderchest/

**Comment by Jikoo** [comment]
If you're having trouble with OpenInv overriding /ec, you can always use Bukkit's [command.yml](http://wiki.bukkit.org/Commands.yml) feature to fix it:
```yaml
aliases:
  ec:
  - customenderchest $1-
```
